Methods to generate DialogNodes for watson exporter
Botmock/sdk pull request #489
Opened 2020-10-20 20:48 UTC by rahulchauhan049

Fix #403 

This PR works on creating methods to generate dialog nodes for watson exporter.

When a project is exported then it should create correct dialog nodes including variables, conditions, slots. 

See the JSON below which is exported from Watson.

[skill-Customer-Care-Sample-Skill.json.zip](https://github.com/Botmock/sdk/files/5162744/skill-Customer-Care-Sample-Skill.json.zip)

Please follow this link to understand the JSON they export:
https://cloud.ibm.com/docs/assistant-data?topic=assistant-data-api-dialog-modify

2020-10-29 11:25 UTC, Gauhar commented on packages/export/src/watson/index.ts
> +          let condition;
why do we have `let condition` in two places? :-/

2020-10-29 11:58 UTC, obaid requested changes
Let's chat about this sometime today.

2020-10-29 11:58 UTC, obaid commented on packages/export/src/watson/index.ts
> -    [Botmock.SystemEntity.NAME, Watson.SystemEntity.PERSON],
Are we removing these since they are now deprecated in Watson?

2020-10-29 11:58 UTC, obaid commented on packages/export/src/watson/index.ts
> +  #findNameOfIntent = (id: string) => {
Let's rename this to: `getIntentName`
```suggestion
  #getIntentName = (id: string) => {
```

2020-10-29 11:58 UTC, obaid commented on packages/export/src/watson/index.ts
> +  #findConditionsOfIntent = (item) => {
I would rename this to `getIntentConditions` and the parameter needs to be renamed from item to `intent`

2020-10-29 11:58 UTC, obaid commented on packages/export/src/watson/index.ts
> +  #findConditionsOfIntent = (item) => {
and we should type cast our parameter

2020-10-29 11:58 UTC, obaid commented on packages/export/src/watson/index.ts
> +  #transform = (block, paths, index) => {
Let's add types to parameters.. and I think we should make this method name more descriptive.. I am not sure what is it transforming and to what?

2020-10-29 11:58 UTC, obaid commented on packages/export/src/watson/index.ts
> +  #getVariablesCharactersFromMessage = ( text: string, paths?: any[], currentPathIndex?: number):any => {
Is this specific to watson?

2020-10-29 11:58 UTC, obaid commented on packages/export/src/watson/index.ts
> +              } catch { }
what happens if the `try` fails here? should we give a default value to `responses` in `catch`?

2020-10-29 11:58 UTC, obaid commented on packages/export/src/watson/index.ts
> +        })
we are mapping over messages a lot here.. I think it would make it more readable if we create methods to do this...
`messages.map(this.doSomeMapping)`?

2020-10-29 11:58 UTC, obaid commented on packages/export/src/watson/index.ts
> +        });
another map here.. (see my comment below)

2020-10-29 11:58 UTC, obaid commented on packages/export/src/watson/index.ts
> +  #generateDialogNodes = (pathsMappedByIntents) => {
This method is way toooo long for my liking. Let's break it down into smaller submethods.

2020-10-29 11:58 UTC, obaid commented on packages/export/src/watson/index.ts
> +    ) => {
formatting..

2020-10-29 11:58 UTC, obaid commented on packages/export/src/watson/index.ts
> +  #replaceVariableCharacterInText = ( text: string, paths?: any[], currentPathIndex?: number ): string => {
This looks verry similar to `getVariablesCharactersFromMessage`.....

2020-10-29 11:58 UTC, obaid commented on packages/export/src/watson/index.ts
>              minorVersion: "2018-11-08",
we should dynamically generate proper date here..

2020-10-29 14:11 UTC, rahulchauhan049 commented on packages/export/src/watson/index.ts
> -    [Botmock.SystemEntity.NAME, Watson.SystemEntity.PERSON],
Yes, these are now deprecated

2020-10-30 15:27 UTC, obaid requested changes

2020-10-30 15:27 UTC, obaid commented on packages/export/src/watson/index.ts
> +    return intent[0].name;
We should check if this intent was found or not. Otherwise this would crash.

2020-10-30 15:27 UTC, obaid commented on packages/export/src/watson/index.ts
> +    const intent = this.resources.intents.filter((intent) => intent.id === id);
perhaps use `find` instead of `filter`?

2020-10-30 15:27 UTC, obaid commented on packages/export/src/watson/index.ts
> +       let messageBlock = this.resources.board.board.messages.flatMap(
formatting

2020-10-30 15:27 UTC, obaid commented on packages/export/src/watson/index.ts
> +      if(messageBlock.conditional.rules.length > 0){
These two can be combined:


```suggestion
    if(messageBlock.conditional?.rules?.length > 0){
```

2020-11-03 01:55 UTC, obaid approved these changes

2020-11-03 01:55 UTC, obaid commented
@Gauhar & @rahulchauhan049 is this ready for merge?

2020-11-03 19:09 UTC, merged